apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 80
      nodePort: 30009
  selector:
    app: helloworld
    type: front-end