apiVersion: v1
kind: Pod
metadata:
  name: print-greeting-configmap
spec:
  containers: 
    - image: bash
      name: env-print-demo
      env: 
      - name: GREETING
        valueFrom:
          configMapKeyRef:
            name: example-config
            key: GREETING
      - name: HONORIFIC
        valueFrom:
          configMapKeyRef:
            name: example-config
            key: HONORIFIC
      - name: NAME
        valueFrom:
          configMapKeyRef:
            name: example-config
            key: NAME
      command: ["echo"]
      args: [ "$(GREETING) $(HONORIFIC) $(NAME)" ]
  restartPolicy: Never